// SOC2 task estimates — CODE-CHANGE effort only, single developer familiar with the codebase.
// d = [lo, hi] engineer-days for the frontend/backend code change (incl. its own unit tests).
// DevOps / AWS / infra / credential-rotation / git-history / policy work is NOT counted in d.
//   It is listed explicitly per finding in opsEn/opsZh (handled separately).
// conf: High | Med | Low | Discuss   (Discuss = scope/policy decision needed before sizing)
// g: work-group key (see GROUPS)

const GROUPS = {
  G1:  { en: 'Secrets removal & rotation', zh: '密钥清除与轮换' },
  G2:  { en: 'Config & secret externalization', zh: '配置与密钥外部化' },
  G3:  { en: 'JWT & token integrity', zh: 'JWT 与令牌完整性' },
  G4:  { en: 'Token lifecycle & revocation', zh: '令牌生命周期与吊销' },
  G5:  { en: 'Authorization & multi-tenancy', zh: '授权与多租户' },
  G6:  { en: 'MFA / strong authentication', zh: '多因素认证 / 强身份验证' },
  G7:  { en: 'Password & reset-flow security', zh: '口令与重置流程安全' },
  G8:  { en: 'Encryption in transit (TLS)', zh: '传输加密（TLS）' },
  G9:  { en: 'Security headers / CORS / CSP', zh: '安全响应头 / CORS / CSP' },
  G10: { en: 'Injection fixes', zh: '注入漏洞修复' },
  G11: { en: 'Input validation', zh: '输入校验' },
  G12: { en: 'Crypto at rest & weak crypto', zh: '静态加密与弱加密' },
  G13: { en: 'Logging hygiene & PII redaction', zh: '日志脱敏与 PII' },
  G14: { en: 'Audit logging & log integrity', zh: '审计日志与日志完整性' },
  G15: { en: 'Rate limiting & DoS resilience', zh: '限流与抗 DoS' },
  G16: { en: 'Dependency upgrades', zh: '依赖升级' },
  G17: { en: 'CI/CD security & change management', zh: 'CI/CD 安全与变更管理' },
  G18: { en: 'Infra/IaC, IAM & deploy resilience', zh: '基础设施/IaC、IAM 与部署韧性' },
  G19: { en: 'Privacy & data lifecycle', zh: '隐私与数据生命周期' },
  G20: { en: 'Misc hardening', zh: '其他加固' },
};

const CONF = {
  High:    { en: 'High',    zh: '高' },
  Med:     { en: 'Medium',  zh: '中' },
  Low:     { en: 'Low',     zh: '低' },
  Discuss: { en: 'Discuss', zh: '待讨论' },
};

const EST = {
  'SEC-001': { d:[0.5,1], conf:'Med', g:'G3',
    en:'Code: read the signing key from config/env instead of the hardcoded literal; optionally switch to RS256/ES256 (changes the sign/verify calls). Small if symmetric-externalize only; ~1d if you also do asymmetric.',
    zh:'代码：改为从配置/环境读取签名密钥而非硬编码；可选切换 RS256/ES256（改动签名/验签调用）。仅对称外部化很小；若同时改非对称约 1 天。',
    opsEn:['Generate a >=256-bit key per environment and store it in AWS Secrets Manager','Rotate the key and invalidate existing tokens (coordinated redeploy)','Purge the literal from git history'],
    opsZh:['为每个环境生成 ≥256 位密钥并存入 AWS Secrets Manager','轮换密钥并使现有令牌失效（协调重新部署）','从 Git 历史清除该明文'] },
  'SEC-002': { d:[0.25,0.25], conf:'High', g:'G1',
    en:'Code: replace the template token value with a placeholder, source from the secret store, and remove the RUN echo from the Dockerfile. Trivial edit.',
    zh:'代码：将模板中的令牌替换为占位符、改从密钥库读取，并移除 Dockerfile 中的 RUN echo。改动极小。',
    opsEn:['Revoke & rotate the Git PAT and the recoverable git password (treat as compromised)','Purge both from git history (BFG/filter-repo), force-push, all devs re-clone','Inject git auth at runtime from Secrets Manager'],
    opsZh:['吊销并轮换 Git PAT 与可恢复的 git 口令（视为已泄露）','从 Git 历史清除二者（BFG/filter-repo），强制推送，所有人重新克隆','运行时从 Secrets Manager 注入 git 认证'] },
  'SEC-003': { d:[0.25,0.25], conf:'High', g:'G1',
    en:'Code: git rm --cached the tracked keystore/key so the existing .gitignore takes effect. Minimal repo change.',
    zh:'代码：对已跟踪的 keystore/密钥执行 git rm --cached，使现有 .gitignore 生效。仓库改动极小。',
    opsEn:['Rotate the TLS cert/keypair and DER key (assume compromised), set a strong keystore password','Purge the files + password from git history','Provision the keystore/password at deploy time from Secrets Manager'],
    opsZh:['轮换 TLS 证书/密钥对与 DER 密钥（视为已泄露），设置强 keystore 口令','从 Git 历史清除文件与口令','部署时从 Secrets Manager 下发 keystore/口令'] },
  'SEC-004': { d:[0.25,0.25], conf:'High', g:'G1',
    en:'Code: remove the hardcoded ShareFile creds/OAuth secret, read from config. Trivial.',
    zh:'代码：移除硬编码的 ShareFile 凭据/OAuth secret，改从配置读取。改动极小。',
    opsEn:['Rotate the ShareFile account password and OAuth client secret (needs ShareFile admin)','Purge from git history'],
    opsZh:['轮换 ShareFile 账号口令与 OAuth client secret（需 ShareFile 管理员）','从 Git 历史清除'] },
  'SEC-005': { d:[0.25,0.5], conf:'High', g:'G9',
    en:'Code: CorsConfig edit — drop the wildcard origin pattern, set allowCredentials(false), list explicit methods/headers. Verify each env SPA origin still works.',
    zh:'代码：修改 CorsConfig——去除通配来源、allowCredentials(false)、显式列出方法/头。验证各环境前端来源仍可用。',
    opsEn:[], opsZh:[] },
  'SEC-006': { d:[0.5,0.5], conf:'High', g:'G8',
    en:'Code: remove the accepting TrustStrategy + NoopHostnameVerifier in the two REST clients, delete turnOffSslChecking(), remove http.sslVerify false from the Dockerfile.',
    zh:'代码：移除两个 REST 客户端中的信任全部 TrustStrategy 与 NoopHostnameVerifier，删除 turnOffSslChecking()，并从 Dockerfile 移除 http.sslVerify false。',
    opsEn:['Import the internal/private CA into the JVM/dedicated truststore on the hosts'],
    opsZh:['在主机上将内部/私有 CA 导入 JVM/专用 truststore'] },
  'SEC-007': { d:[0.5,1], conf:'Med', g:'G10',
    en:'Code: invoke git via an explicit argv ProcessBuilder (no shell) and allowlist-validate repo/tag/branch names. Regression-test the diff/clone flow.',
    zh:'代码：用显式 argv 的 ProcessBuilder 调用 git（不经 shell），并对仓库/标签/分支名做白名单校验。对 diff/clone 流程回归测试。',
    opsEn:[], opsZh:[] },
  'SEC-008': { d:[0.25,0.5], conf:'High', g:'G10',
    en:'Code: escape/encode the email in the SOQL (or use bind variables) + add @Email validation. Single method.',
    zh:'代码：对 SOQL 中的 email 做转义/编码（或用绑定变量）并加 @Email 校验。单方法。',
    opsEn:[], opsZh:[] },
  'SEC-009': { d:[1,2], conf:'Med', g:'G5',
    en:'Code: implement a real PermissionEvaluator receiving the target id (fix the #targert typo), enforce object/tenant entitlement in the service layer across the resource-by-id endpoints, add cross-tenant denial tests. Cross-cutting but bounded; shares the core with SEC-072.',
    zh:'代码：实现接收目标 id 的真实 PermissionEvaluator（修复 #targert 拼写），在服务层对按 id 资源端点强制对象/租户权限，并补跨租户拒绝测试。跨切面但可控；与 SEC-072 共用核心。',
    opsEn:[], opsZh:[] },
  'SEC-010': { d:[1,2], conf:'Discuss', g:'G3',
    en:'Code (once the model is decided): derive the refreshed token identity from the verified refresh token and reject audience/subject mismatch; stop trusting a signature-only audience claim. Needs a decision on how services authenticate (per-service credential vs mTLS) before sizing.',
    zh:'代码（确定方案后）：刷新令牌的身份从已验证的刷新令牌派生并拒绝 audience/subject 不一致；不再信任仅有签名的 audience。需先决定服务认证方式（按服务凭据 vs mTLS）再定量。',
    opsEn:['Decide & provision per-service credentials or mTLS for service identities'],
    opsZh:['决定并下发按服务的凭据或 mTLS 用于服务身份'] },
  'SEC-011': { d:[0.5,0.5], conf:'High', g:'G13',
    en:'Code: remove the blanket response-body serialization in the logging aspect, log only method+status, add field masking and CRLF stripping. Central aspect, well-bounded.',
    zh:'代码：移除日志切面中对响应体的全量序列化，仅记录方法+状态，加字段脱敏与 CRLF 过滤。公共切面，范围明确。',
    opsEn:[], opsZh:[] },
  'SEC-012': { d:[0.5,0.5], conf:'Med', g:'G2',
    en:'Code: Jenkinsfile change to stop bundling the config dir into the artifact; app already supports the prod profile sourcing from the secret store.',
    zh:'代码：修改 Jenkinsfile，不再将 config 目录打包进制品；应用的 prod profile 已支持从密钥库读取。',
    opsEn:['Deliver runtime config/keystore via Secrets Manager/SSM at boot','Rotate key material once history is purged'],
    opsZh:['启动时通过 Secrets Manager/SSM 下发运行时配置/keystore','历史清除后轮换密钥材料'] },
  'SEC-013': { d:[0.5,1], conf:'Med', g:'G18',
    en:'IaC: edit the CloudFormation JSON to least-privilege actions, scope resource ARNs, and restrict iam:PassRole. Needs you to enumerate the pipeline\'s real actions.',
    zh:'IaC：修改 CloudFormation JSON 为最小权限动作、限定资源 ARN 并约束 iam:PassRole。需梳理流水线实际所需动作。',
    opsEn:['Add an IAM linter (cfn-nag/checkov) to the pipeline','Validate the scoped policy in a real deploy'],
    opsZh:['在流水线加入 IAM 检查器（cfn-nag/checkov）','在真实部署中验证收敛后的策略'] },
  'SEC-014': { d:[0.5,0.5], conf:'Med', g:'G8',
    en:'Config: add the TLS listener + 80->443 redirect + upstream-over-TLS in reverse_proxy.nginx.conf. Code/config side is small.',
    zh:'配置：在 reverse_proxy.nginx.conf 增加 TLS 监听、80->443 跳转与上游走 TLS。代码/配置侧很小。',
    opsEn:['Provision valid TLS certs and decide the production TLS-termination point'],
    opsZh:['下发有效 TLS 证书并确定生产 TLS 终止点'] },
  'SEC-015': { d:[0.25,0.25], conf:'High', g:'G8',
    en:'Config: remove sslfactory=NonValidatingFactory, set sslmode=verify-full + sslrootcert. One-line property change.',
    zh:'配置：移除 sslfactory=NonValidatingFactory，设置 sslmode=verify-full 与 sslrootcert。单行属性改动。',
    opsEn:['Place the RDS CA bundle on the hosts'],
    opsZh:['在主机上放置 RDS CA 包'] },
  'SEC-016': { d:[0.25,0.5], conf:'Med', g:'G12',
    en:'Code: change EncryptorConfig to PBEWITHHMACSHA512ANDAES_256 with high iterations + random IV. Small code change.',
    zh:'代码：将 EncryptorConfig 改为 PBEWITHHMACSHA512ANDAES_256、高迭代次数与随机 IV。代码改动小。',
    opsEn:['Re-encrypt all stored secrets across environments and coordinate the rollout'],
    opsZh:['在各环境重新加密全部已存密文并协调上线'] },
  'SEC-017': { d:[0.25,0.5], conf:'High', g:'G12',
    en:'Code: swap RandomStringUtils/java.util.Random for SecureRandom at the token/password sites; widen charset, keep tokens single-use. A few call sites.',
    zh:'代码：在令牌/口令生成处把 RandomStringUtils/java.util.Random 换成 SecureRandom；扩大字符集、保持令牌单次使用。涉及少量调用点。',
    opsEn:[], opsZh:[] },
  'SEC-018': { d:[0.5,0.5], conf:'High', g:'G20',
    en:'Code: dedicated authenticated actuator SecurityFilterChain, limit exposure to health/info, remove the static admin/secret, delete dead management.security.* props.',
    zh:'代码：为 actuator 配置受保护的 SecurityFilterChain，仅暴露 health/info，移除静态 admin/secret，删除失效的 management.security.* 配置。',
    opsEn:['Bind the management port to localhost or drop the 8081 host mapping (compose)'],
    opsZh:['将管理端口绑定到 localhost 或在 compose 移除 8081 主机映射'] },
  'SEC-019': { d:[0.5,1], conf:'Med', g:'G15',
    en:'Code: add a LoginAttemptService / Bucket4j failed-attempt + lockout + backoff on /auth/* with tests. New but small mechanism; shares code with SEC-031.',
    zh:'代码：为 /auth/* 增加 LoginAttemptService / Bucket4j 失败计数+锁定+退避并加测试。新增但机制小；与 SEC-031 共用代码。',
    opsEn:['Optionally add nginx limit_req/limit_conn (config)'],
    opsZh:['可选：增加 nginx limit_req/limit_conn（配置）'] },
  'SEC-020': { d:[1,2], conf:'Med', g:'G4',
    en:'Code (front+back): server sets httpOnly+Secure+SameSite cookies (or keep tokens in-memory; exclude the token sub-state from the persisted NGXS key), plus CSRF handling. Genuine front/back integration — not a single-file change.',
    zh:'代码（前后端）：服务端下发 httpOnly+Secure+SameSite Cookie（或令牌仅存内存；将令牌子状态排除出持久化的 NGXS key），并处理 CSRF。属真实前后端联调——非单文件改动。',
    opsEn:[], opsZh:[] },
  'SEC-021': { d:[0.25,0.5], conf:'High', g:'G20',
    en:'Code: run DOMPurify.sanitize() on the readonly markdown path (mirror the editor path), centralize through one sanitize() helper, disable raw HTML in marked. Single component.',
    zh:'代码：在只读 markdown 路径调用 DOMPurify.sanitize()（与编辑路径一致），统一走一个 sanitize() 入口，并在 marked 关闭原始 HTML。单组件。',
    opsEn:[], opsZh:[] },
  'SEC-022': { d:[0.25,0.25], conf:'High', g:'G20',
    en:'Code: drive signatureDuration from the configured expireMinutes and clamp bad values. Single method.',
    zh:'代码：让 signatureDuration 由配置的 expireMinutes 驱动并对异常值夹取。单方法。',
    opsEn:[], opsZh:[] },
  'SEC-023': { d:[0.25,0.5], conf:'High', g:'G1',
    en:'Code: inject the webhook secret via @Value, compare HMACs with MessageDigest.isEqual (constant-time), validate header shape, stop logging signatures. Localized controller change.',
    zh:'代码：用 @Value 注入 webhook secret，用 MessageDigest.isEqual 做常量时间比较，校验头格式并停止记录签名。控制器局部改动。',
    opsEn:['Store a high-entropy webhook secret in the secret store and rotate "netbrain"'],
    opsZh:['在密钥库存放高熵 webhook secret 并轮换 “netbrain”'] },
  'SEC-024': { d:[1,3], conf:'Discuss', g:'G16',
    en:'Code: migrate fastjson 1.x off (standardize on Jackson, or fastjson2 with safeMode) — touches every fastjson usage — and bump marked/dompurify/bootstrap/rxjs/core-js. Heavy regression; scope the fastjson migration before committing.',
    zh:'代码：迁移 fastjson 1.x（统一用 Jackson，或 fastjson2 安全模式）——牵动所有 fastjson 用法——并升级 marked/dompurify/bootstrap/rxjs/core-js。回归量大；fastjson 迁移范围需先评估。',
    opsEn:['Re-run SCA after the upgrades'],
    opsZh:['升级后重新运行 SCA'] },
  'SEC-025': { d:[0.5,1], conf:'Med', g:'G17',
    en:'CI config: add waitForQualityGate(abort) after Sonar, add SCA (Dependency-Check/npm audit) and a secret scanner (gitleaks) as failing stages in both Jenkinsfiles.',
    zh:'CI 配置：在 Sonar 后加 waitForQualityGate(中止)，并在两条 Jenkinsfile 加入 SCA（Dependency-Check/npm audit）与密钥扫描（gitleaks）作为失败阶段。',
    opsEn:['Enable Dependabot/Renovate on both repos'],
    opsZh:['在两个仓库启用 Dependabot/Renovate'] },
  'SEC-026': { d:[0.5,1], conf:'Med', g:'G17',
    en:'Code/config: declare a non-root USER in both Dockerfiles, pin base images by digest, forbid :latest, point compose at the org registry. Repo-side change is small.',
    zh:'代码/配置：在两个 Dockerfile 声明非 root USER，按摘要锁定基础镜像，禁用 :latest，并将 compose 指向组织镜像仓库。仓库侧改动小。',
    opsEn:['Stand up an org-owned private registry (ECR) with immutable tags + signing (cosign)','Add image scanning (Trivy/Grype) and scope CodeDeploy hooks to least privilege'],
    opsZh:['搭建组织自有私有镜像仓库（ECR），不可变标签 + 签名（cosign）','加入镜像扫描（Trivy/Grype），并将 CodeDeploy hook 收敛到最小权限'] },
  'SEC-027': { d:[0.5,1], conf:'Med', g:'G19',
    en:'Code: a scheduled job honouring whenResolvedDeleteData that purges resolved-ticket PII + expired tokens. Code is small once the retention period is set.',
    zh:'代码：一个按 whenResolvedDeleteData 执行的定时作业，清理已解决工单的 PII 与过期令牌。确定留存期后代码量小。',
    opsEn:['Agree & document the retention/deletion policy (retention periods)'],
    opsZh:['确定并文档化留存/删除策略（留存期）'] },
  'SEC-028': { d:[1,2], conf:'Med', g:'G14',
    en:'Code (cross-cutting): a Spring Security AccessDeniedHandler + audit calls for auth failures, logout, account-disabled, and IAM CRUD with before/after. Spread across several controllers; shares the audit mechanism with SEC-067.',
    zh:'代码（跨切面）：Spring Security AccessDeniedHandler，并为登录失败、登出、账号停用与 IAM CRUD（前后值）加审计调用。分布在多个控制器；与 SEC-067 共用审计机制。',
    opsEn:['Forward audit events to centralized logging/SIEM with threshold alerting'],
    opsZh:['将审计事件转发到集中日志/SIEM 并设阈值告警'] },
  'SEC-029': { d:[0.5,1], conf:'Med', g:'G14',
    en:'Code: make audit storage append-only — restrict AuditRepository to a save-only interface; add the log4j2 appender config. The rest is infra.',
    zh:'代码：将审计存储改为仅追加——把 AuditRepository 限制为只写接口；并加 log4j2 appender 配置。其余为基础设施。',
    opsEn:['Add CloudWatch/Firehose appender shipping to an append-only/immutable destination (S3 Object Lock + retention)','INSERT-only DB grant (revoke UPDATE/DELETE) on the audit table','Alerting on auth-failure/authz-denial events'],
    opsZh:['增加 CloudWatch/Firehose appender，输出到仅追加/不可变目的地（S3 Object Lock + 留存）','对审计表设置仅 INSERT 的数据库授权（吊销 UPDATE/DELETE）','对登录失败/授权拒绝事件设置告警'] },
  'SEC-030': { d:[0.25,0.25], conf:'High', g:'G13',
    en:'Code: remove the specific token/license log statements and grep for similar sinks. Trivial.',
    zh:'代码：删除特定的令牌/许可证日志语句并 grep 排查同类输出点。改动极小。',
    opsEn:['Scrub historical logs that already contain tokens'],
    opsZh:['清理已包含令牌的历史日志'] },
  'SEC-031': { d:[0.25,0.5], conf:'Med', g:'G15',
    en:'Code: per-IP/per-account rate limiting at the app layer (mostly shared with SEC-019). Marginal if built together.',
    zh:'代码：应用层按 IP/账号限流（大部分与 SEC-019 共用）。一并实现时为增量。',
    opsEn:['nginx limit_req/limit_conn + sane client_max_body_size for non-upload routes (config)','Right-size and monitor the Hikari pool'],
    opsZh:['为非上传路由配置 nginx limit_req/limit_conn 与合理的 client_max_body_size','调整并监控 Hikari 连接池'] },
  'SEC-032': { d:[0.25,0.5], conf:'High', g:'G2',
    en:'Config: replace hardcoded DB passwords in compose/properties with env/Docker-secret indirection; remove packaged defaults.',
    zh:'配置：将 compose/properties 中硬编码的数据库口令改为 env/Docker secret 引用；移除打包默认值。',
    opsEn:['Rotate "Netbrain!"','Source values from a gitignored .env or AWS Secrets Manager'],
    opsZh:['轮换 “Netbrain!”','从被 gitignore 的 .env 或 AWS Secrets Manager 读取值'] },
  'SEC-033': { d:[0.25,0.25], conf:'High', g:'G1',
    en:'Code: remove Jasypt master passwords from test resources, inject from env, delete the dead ticket EncryptorConfig. Small.',
    zh:'代码：从测试资源移除 Jasypt 主口令、改从 env 注入，并删除失效的 ticket EncryptorConfig。改动小。',
    opsEn:['Rotate "erumc323"/"netbrain-kc" if reused outside tests'],
    opsZh:['若在测试外复用过，轮换 “erumc323”/“netbrain-kc”'] },
  'SEC-034': { d:[0.25,0.5], conf:'High', g:'G7',
    en:'Code: enforce min-length/complexity on the server in updatePassword/save/update/reset paths. Localized validation.',
    zh:'代码：在 updatePassword/save/update/reset 路径加服务端最小长度/复杂度校验。属局部校验。',
    opsEn:[], opsZh:[] },
  'SEC-035': { d:[0.5,0.5], conf:'Med', g:'G7',
    en:'Code: identical generic response from sendResetLink, single-use short-lived tokens, drop email/username from public verify. Touches the reset flow; overlaps SEC-071.',
    zh:'代码：sendResetLink 返回一致的通用响应、令牌单次且短时效、公开校验不返回 email/username。涉及重置流程；与 SEC-071 重叠。',
    opsEn:[], opsZh:[] },
  'SEC-036': { d:[0.25,0.5], conf:'High', g:'G5',
    en:'Code: add method-level @PreAuthorize on syncRepo/syncDeltaChange and change hasPrivilege from substring to equals. Shares the equality fix with SEC-062.',
    zh:'代码：为 syncRepo/syncDeltaChange 加方法级 @PreAuthorize，并将 hasPrivilege 从子串改为相等。与 SEC-062 共用相等性修复。',
    opsEn:[], opsZh:[] },
  'SEC-037': { d:[1,2], conf:'Med', g:'G11',
    en:'Code: add @Valid + dedicated request DTOs with Bean Validation constraints across many controllers, restore the commented-out Ticket constraints. Breadth drives the cost, but each edit is small.',
    zh:'代码：在多个控制器加 @Valid 与带约束的请求 DTO，并恢复被注释的 Ticket 约束。成本来自覆盖面，但单处改动小。',
    opsEn:[], opsZh:[] },
  'SEC-038': { d:[0.5,0.5], conf:'High', g:'G10',
    en:'Code: sanitize uploaded filenames (FilenameUtils.getName / server-generated name) and canonicalize+contain each unzip entry. Two well-defined sinks.',
    zh:'代码：净化上传文件名（FilenameUtils.getName / 服务端生成名）并对每个解压条目做规范化+包含校验。两个明确注入点。',
    opsEn:[], opsZh:[] },
  'SEC-039': { d:[0.25,0.25], conf:'High', g:'G8',
    en:'Code/config: set mail.smtp.starttls.required + ssl.checkserveridentity on the custom SMTP path. Property-level.',
    zh:'代码/配置：在自定义 SMTP 路径设置 mail.smtp.starttls.required 与 ssl.checkserveridentity。属性级改动。',
    opsEn:[], opsZh:[] },
  'SEC-040': { d:[0.5,0.5], conf:'Med', g:'G12',
    en:'Code: hash over the entire package (stream the full file) and fix both the byte[] and File overloads, or hard-fail oversized packages. Regression-test the upgrade verify path.',
    zh:'代码：对整个升级包计算摘要（流式读取全文件），修复 byte[] 与 File 两个重载，或对超限包直接报错。对升级验签路径回归测试。',
    opsEn:[], opsZh:[] },
  'SEC-041': { d:[0.5,0.5], conf:'High', g:'G20',
    en:'Code: replace web.ignoring() with permitAll() inside authorizeHttpRequests, tighten the path list, gate /webhooks behind signature verification (SEC-023).',
    zh:'代码：用 authorizeHttpRequests 内的 permitAll() 替换 web.ignoring()，收紧路径列表，并用签名校验保护 /webhooks（SEC-023）。',
    opsEn:['Disable springdoc/swagger in internet-reachable non-prod (config/env)'],
    opsZh:['在可被公网访问的非生产环境关闭 springdoc/swagger（配置/环境）'] },
  'SEC-042': { d:[0.5,1], conf:'High', g:'G13',
    en:'Code: generic 5xx message + correlation id, replace printStackTrace with logger.error, route frontend logging through the env-gated LogService, add a no-console lint rule. A few central spots.',
    zh:'代码：5xx 返回通用消息+关联 id，用 logger.error 替换 printStackTrace，前端日志走环境网关的 LogService，并加 no-console 规则。涉及少量公共位置。',
    opsEn:[], opsZh:[] },
  'SEC-043': { d:[0.5,1], conf:'Med', g:'G14',
    en:'Code: attribute audited export/read to the authenticated UserEntity (Actor.getActor()) instead of licenseId/robot, cover UI reads, null-guard getActor(), add an MDC correlation id. Overlaps SEC-028.',
    zh:'代码：将导出/读取审计归属到已认证的 UserEntity（Actor.getActor()）而非 licenseId/robot，覆盖 UI 读取，对 getActor() 做空值保护，并加 MDC 关联 id。与 SEC-028 重叠。',
    opsEn:[], opsZh:[] },
  'SEC-044': { d:[0.25,0.25], conf:'High', g:'G15',
    en:'Config: lower max-file/request-size, set a spill-to-disk threshold, apply across profiles. Verify the legit package-upload still works.',
    zh:'配置：下调 max-file/request-size、设置落盘阈值并在各 profile 一致。验证合法升级包上传仍可用。',
    opsEn:['nginx client_max_body_size + limit_req (config)'],
    opsZh:['nginx client_max_body_size + limit_req（配置）'] },
  'SEC-045': { d:[0.25,0.25], conf:'High', g:'G12',
    en:'Code: set .serverSideEncryption(AWS_KMS) on every PutObjectRequest. A few call sites.',
    zh:'代码：在每个 PutObjectRequest 设置 .serverSideEncryption(AWS_KMS)。涉及少量调用点。',
    opsEn:['Bucket policy denying unencrypted PutObject + confirm bucket default encryption'],
    opsZh:['桶策略拒绝未加密 PutObject，并确认桶默认加密'] },
  'SEC-046': { d:[0.5,1], conf:'Med', g:'G9',
    en:'Code/config: add a restrictive CSP + X-Frame-Options/nosniff/Referrer-Policy at nginx and extend the app filter (Permissions-Policy, frame-ancestors, base-uri). CSP-without-unsafe-inline needs iterative tuning so the SPA does not break — that is the time.',
    zh:'代码/配置：在 nginx 加严格 CSP + X-Frame-Options/nosniff/Referrer-Policy 并扩展应用过滤器（Permissions-Policy、frame-ancestors、base-uri）。不含 unsafe-inline 的 CSP 需反复调试以免影响 SPA——这是主要耗时。',
    opsEn:['Add HSTS at the TLS-terminating layer'],
    opsZh:['在 TLS 终止层加 HSTS'] },
  'SEC-047': { d:[0.25,0.5], conf:'High', g:'G1',
    en:'Code: scrub PII-shaped seed/fixture values, regenerate unique hashes, remove the committed Jasypt master password from data fixtures. Localized data files.',
    zh:'代码：清理 PII 形态的种子/夹具数据，重新生成唯一哈希，从数据夹具移除提交的 Jasypt 主口令。仅数据文件。',
    opsEn:[], opsZh:[] },
  'SEC-048': { d:[0.5,1], conf:'Med', g:'G16',
    en:'Code: upgrade gson, drop the reactor pin, pin the RELEASE metaversion, re-verify the XML stack. HttpClient 5 (if attempted) pushes to the high end.',
    zh:'代码：升级 gson、移除 reactor 固定版本、固定 RELEASE 元版本、复核 XML 栈。若尝试 HttpClient 5 则偏高端。',
    opsEn:[], opsZh:[] },
  'SEC-049': { d:[1,2], conf:'Med', g:'G17',
    en:'CI config: several distinct Jenkinsfile fixes — gating test stage, remove npm --force, OIDC token to a 0600 mktemp file cleaned in finally, per-env credentials, named prod approver, parameterize account ids. Each small but they add up.',
    zh:'CI 配置：多项 Jenkinsfile 修复——测试门禁阶段、移除 npm --force、OIDC 令牌写入 0600 的 mktemp 文件并在 finally 清理、按环境凭据、指定生产审批人、参数化账号 id。单项小但累加。',
    opsEn:['Artifact signing infra (cosign/KMS) + verify at deploy','Distinct per-environment OIDC roles scoped by branch/subject'],
    opsZh:['制品签名基础设施（cosign/KMS）并在部署时验签','按分支/主体限定的、各环境独立的 OIDC 角色'] },
  'SEC-050': { d:[0.25,0.25], conf:'High', g:'G10',
    en:'Code: URL-encode the dynamic path in the ShareFile getItemByPath call + pattern-validate. Trivial.',
    zh:'代码：对 ShareFile getItemByPath 调用中的动态路径做 URL 编码并加模式校验。改动极小。',
    opsEn:[], opsZh:[] },
  'SEC-051': { d:[0.25,0.25], conf:'High', g:'G10',
    en:'Code: enable FreeMarker HTML auto-escaping (output_format=HTML / rename to .ftlh) so all ${} are escaped. Small.',
    zh:'代码：启用 FreeMarker HTML 自动转义（output_format=HTML / 改名 .ftlh）使所有 ${} 转义。改动小。',
    opsEn:[], opsZh:[] },
  'SEC-052': { d:[0.5,0.5], conf:'Med', g:'G12',
    en:'Code: replace MD5 with SHA-256 in the helpers and use Signature.getInstance("SHA256withRSA").verify() for license checks instead of manual Cipher+Arrays.equals. Confirm existing licenses still validate.',
    zh:'代码：将辅助方法中的 MD5 换成 SHA-256，许可证校验改用 Signature.getInstance("SHA256withRSA").verify() 而非手写 Cipher+Arrays.equals。确认现有许可证仍可通过。',
    opsEn:[], opsZh:[] },
  'SEC-053': { d:[0.25,0.25], conf:'High', g:'G2',
    en:'Code: move license.key out of the committed config template into the Secrets Manager bundle. No rotation emergency. Small move.',
    zh:'代码：将 license.key 从提交的配置模板移入 Secrets Manager 包。无紧急轮换。小幅迁移。',
    opsEn:[], opsZh:[] },
  'SEC-054': { d:[0.5,1], conf:'Med', g:'G20',
    en:'Code (frontend): bundle of small fixes — origin-check before attaching the bearer, same-origin returnUrl validation, render text instead of [innerHTML], crypto.randomUUID for guid(). Several small edits.',
    zh:'代码（前端）：一批小修复——附加 bearer 前校验来源、returnUrl 限同源、用文本替代 [innerHTML]、guid() 改用 crypto.randomUUID。若干小改动。',
    opsEn:[], opsZh:[] },
  'SEC-055': { d:[0.25,0.5], conf:'Med', g:'G5',
    en:'Code: remove the misleading no-op TenantDomainInterceptor (or document guards as UX only). The real enforcement is the backend authz work (SEC-009/072).',
    zh:'代码：移除有误导性的空操作 TenantDomainInterceptor（或将守卫文档化为仅 UX）。真正的强制在后端授权（SEC-009/072）。',
    opsEn:[], opsZh:[] },
  'SEC-056': { d:[0.25,0.5], conf:'High', g:'G13',
    en:'Code: log opaque ids (user id, hashed license id) instead of email/displayName/full customer JSON; apply layout redaction. Localized.',
    zh:'代码：用不透明 id（用户 id、哈希后的 license id）替代 email/displayName/完整客户 JSON 记录日志，并在布局层脱敏。改动局部。',
    opsEn:[], opsZh:[] },
  'SEC-057': { d:[1,3], conf:'Med', g:'G16',
    en:'Code: migrate e2e protractor -> Playwright/Cypress (the bulk of the work), drop babel6/Storybook4/TSLint tooling, add package.json overrides for transitives. The e2e migration drives this.',
    zh:'代码：将 e2e 从 protractor 迁移到 Playwright/Cypress（主要工作量），移除 babel6/Storybook4/TSLint，并为传递依赖加 package.json overrides。e2e 迁移决定此项。',
    opsEn:[], opsZh:[] },
  'SEC-058': { d:[0.5,1], conf:'High', g:'G16',
    en:'Code: upgrade Mockito to 5.x and JUnit to Jupiter 5 (or >=4.13.2), drop per-module version pins. May need some test-code fixes.',
    zh:'代码：升级 Mockito 到 5.x、JUnit 到 Jupiter 5（或 ≥4.13.2），移除按模块的版本固定。可能需修改部分测试代码。',
    opsEn:[], opsZh:[] },
  'SEC-059': { d:[0.25,0.25], conf:'Discuss', g:'G8',
    en:'Config (after a decision): remove the divergent/commented client-auth settings and make profiles consistent. The work is the architecture decision, not the code.',
    zh:'配置（决策后）：移除分歧/被注释的 client-auth 设置并统一各 profile。工作量在架构决策而非代码。',
    opsEn:['Decide & document whether mTLS is required at the app or proxy boundary'],
    opsZh:['决定并文档化 mTLS 应在应用还是代理边界强制'] },
  'SEC-060': { d:[0.25,0.25], conf:'High', g:'G1',
    en:'Code: remove the onboarding screenshots/test literals from the repo. Trivial.',
    zh:'代码：从仓库移除入职截图/测试字面量。改动极小。',
    opsEn:['Move dev-setup docs to an internal wiki; standardize dev AWS access on SSO/OIDC'],
    opsZh:['将开发环境搭建文档移至内部 wiki；开发者 AWS 访问统一用 SSO/OIDC'] },
  'SEC-061': { d:[3,5], conf:'Discuss', g:'G6',
    en:'Code (front+back): a TOTP/WebAuthn enrollment + verification flow, MFA state on the user, step-up auth for sensitive admin ops, and the frontend enrollment/challenge UI. Genuinely multi-component even for one dev. Decide build-in-app vs federate to an IdP first.',
    zh:'代码（前后端）：TOTP/WebAuthn 的注册+校验流程、用户上的 MFA 状态、敏感管理操作的二次验证，以及前端注册/验证 UI。即便单人也确属多组件。需先决定自建还是联邦到 IdP。',
    opsEn:['If federating: configure the enterprise IdP (OIDC/SAML) and enforce MFA there'],
    opsZh:['若联邦：配置企业 IdP（OIDC/SAML）并在其上强制 MFA'] },
  'SEC-062': { d:[0.25,0.25], conf:'High', g:'G5',
    en:'Code: change hasPrivilege from contains() to equals()/Set membership + a denial unit test. Small but security-critical. Shared with SEC-036.',
    zh:'代码：将 hasPrivilege 从 contains() 改为 equals()/集合判断，并加拒绝单测。改动小但关乎安全。与 SEC-036 共用。',
    opsEn:[], opsZh:[] },
  'SEC-072': { d:[1,2], conf:'Med', g:'G5',
    en:'Code: reimplement CustomPermissionEvaluator to load the target by id and verify it belongs to the principal\'s tenant set, use exact permission equality, reject null/unbound targets. The keystone of app-wide per-tenant authz; add a tenant A-vs-B test matrix.',
    zh:'代码：重写 CustomPermissionEvaluator——按 id 加载目标并校验其属于主体的租户集合，使用精确权限相等，拒绝空/未绑定目标。全应用按租户授权的关键；补 A/B 租户测试矩阵。',
    opsEn:[], opsZh:[] },
  'SEC-073': { d:[1,1.5], conf:'Med', g:'G5',
    en:'Code: bind caller identity to the licenseId being acted on (principal-derived or a per-token license claim), reject mismatches, scope service tokens per license, fix the #targert SpEL. Part of the authz program.',
    zh:'代码：将调用方身份绑定到所操作的 licenseId（由主体派生或按令牌的 license 声明），拒绝不一致，按 license 限定服务令牌，修复 #targert SpEL。属授权工程。',
    opsEn:[], opsZh:[] },
  'SEC-074': { d:[0.5,1], conf:'High', g:'G5',
    en:'Code: add a tenant-scoped finder (findByIdAndCustomerIEInstanceIdIn) and authorize the deployment\'s owning customer before returning logs/links. Bounded once SEC-072 exists.',
    zh:'代码：增加按租户限定的查询（findByIdAndCustomerIEInstanceIdIn），在返回日志/链接前对 deployment 归属客户做授权。SEC-072 就绪后范围明确。',
    opsEn:[], opsZh:[] },
  'SEC-076': { d:[0.25,0.5], conf:'High', g:'G17',
    en:'Code: add a CODEOWNERS file and a real PR template to backend, replace the web stub with a checklist. Small repo files.',
    zh:'代码：为后端添加 CODEOWNERS 文件与真实 PR 模板，将 web 的占位替换为检查清单。仓库小文件。',
    opsEn:['Enable branch protection on develop/release/master in both repos (require PR + non-author review + status checks + dismiss stale)','Retain the exported ruleset as evidence'],
    opsZh:['在两个仓库对 develop/release/master 启用分支保护（要求 PR + 非作者评审 + 状态检查 + 失效评审作废）','保存导出的规则集作为证据'] },
  'SEC-063': { d:[0.25,0.5], conf:'Med', g:'G5',
    en:'Code: drive approver eligibility from explicit permission grants and remove the magic role-id 10000 check; force first-boot rotation of the seeded admin password (data.sql).',
    zh:'代码：审批资格改由显式权限授予驱动并移除魔法 role-id 10000；强制首次启动轮换种子 admin 口令（data.sql）。',
    opsEn:[], opsZh:[] },
  'SEC-064': { d:[1,1.5], conf:'Med', g:'G4',
    en:'Code: short consistent access-token TTL across profiles, remove the 30-day in-jar default, add a server-side revocation mechanism (jti denylist or token-version) checked on each request/refresh, and a real logout endpoint. Shares the revocation core with SEC-066.',
    zh:'代码：各 profile 统一较短的 access token TTL，移除 jar 内 30 天默认值，增加服务端吊销机制（jti 黑名单或令牌版本）在每次请求/刷新校验，并提供真正的登出端点。与 SEC-066 共用吊销核心。',
    opsEn:[], opsZh:[] },
  'SEC-066': { d:[0.5,1], conf:'Med', g:'G4',
    en:'Code: on deactivation/deletion revoke outstanding tokens (token-version/denylist) and re-check isInactive on every request including refresh. Marginal if built with SEC-064.',
    zh:'代码：在停用/删除时吊销在用令牌（令牌版本/黑名单），并在每次请求（含刷新）重校验 isInactive。与 SEC-064 一并实现时为增量。',
    opsEn:[], opsZh:[] },
  'SEC-068': { d:[0.25,0.5], conf:'Med', g:'G14',
    en:'Code/config: raise/remove the max=100/max=1000 caps and the 10MB trigger; separate the audit stream from operational logs. The long-term archive is infra.',
    zh:'代码/配置：放宽/移除 max=100/max=1000 上限与 10MB 触发；将审计流与运营日志分离。长期归档属基础设施。',
    opsEn:['Define & enforce a >=1-year retention for audit logs / audit_log','Archive audit_log on a >=1-year schedule to the immutable destination (with SEC-029)'],
    opsZh:['为审计日志/audit_log 定义并强制 ≥1 年留存','按 ≥1 年计划将 audit_log 归档到不可变目的地（配合 SEC-029）'] },
  'SEC-069': { d:[0.25,0.25], conf:'High', g:'G8',
    en:'Config: set server.ssl.enabled-protocols=TLSv1.2,1.3 + explicit ciphers across active profiles; raise nginx ssl_protocols. A few files.',
    zh:'配置：在各活动 profile 设置 server.ssl.enabled-protocols=TLSv1.2,1.3 与显式加密套件；提升 nginx ssl_protocols。涉及少量文件。',
    opsEn:['Upgrade the JRE to a current LTS','Add a testssl.sh check asserting TLS 1.0/1.1 are refused'],
    opsZh:['将 JRE 升级到当前 LTS','加入 testssl.sh 检查，断言拒绝 TLS 1.0/1.1'] },
  'SEC-070': { d:[0.5,1], conf:'Med', g:'G12',
    en:'Code: stop persisting the package password in cleartext — store a salted hash for verification, or encrypt the column with a KMS-backed AttributeConverter; purge after link-expiry. Includes migrating existing rows.',
    zh:'代码：停止明文存储升级包口令——存可校验的加盐哈希，或用 KMS 支持的 AttributeConverter 加密该列；链接到期后清除。含迁移既有数据。',
    opsEn:[], opsZh:[] },
  'SEC-071': { d:[0.5,0.5], conf:'High', g:'G7',
    en:'Code: store only a SHA-256 hash of a high-entropy reset token, look up by hash, delete after single use. Overlaps SEC-035.',
    zh:'代码：仅存储高熵重置令牌的 SHA-256 哈希，按哈希查找，单次使用后删除。与 SEC-035 重叠。',
    opsEn:[], opsZh:[] },
  'SEC-075': { d:[1,2], conf:'Med', g:'G5',
    en:'Code: filter isDeleted=false in all customer read paths and provide an audited customer-deletion that cascades to per-customer artifacts. Read-filter is small; the cascade (incl. S3/log blobs) is the bulk.',
    zh:'代码：在所有客户读取路径过滤 isDeleted=false，并提供带审计的客户删除以级联到各客户产物。读过滤很小；级联（含 S3/日志 blob）是主要部分。',
    opsEn:['Cascade destruction to S3 objects / deployment-log blobs','Agree a retention period before hard purge'],
    opsZh:['将销毁级联到 S3 对象 / 部署日志 blob','在硬删除前确定留存期'] },
  'SEC-077': { d:[0.25,0.5], conf:'High', g:'G17',
    en:'CI config: never leave the Jenkins approval submitter empty (named approver group distinct from author); fail non-release branches that try to deploy.',
    zh:'CI 配置：Jenkins 审批提交者不留空（指定与作者不同的审批组）；对尝试部署的非发布分支使其失败。',
    opsEn:['Add a CodePipeline manual-approval action before CodeDeploy (or a referenced change ticket)','Log approver identity per production deployment'],
    opsZh:['在 CodeDeploy 前增加 CodePipeline 人工审批动作（或关联变更工单）','每次生产部署记录审批人身份'] },
  'SEC-078': { d:[0.5,1], conf:'Med', g:'G17',
    en:'Code/CI: include semver/git short-SHA in the jar name + S3 key and embed build metadata via the build-info / git-commit-id plugin; stop using SNAPSHOT for releases.',
    zh:'代码/CI：在 jar 名与 S3 key 中加入 semver/git 短 SHA，并通过 build-info / git-commit-id 插件嵌入构建元数据；发布不再用 SNAPSHOT。',
    opsEn:['Record the deployed version per environment'],
    opsZh:['按环境记录已部署版本'] },
  'SEC-079': { d:[0.25,0.5], conf:'Med', g:'G18',
    en:'CI: use versioned/immutable S3 keys so a prior build can be redeployed. The auto-rollback + runbook is mostly AWS config.',
    zh:'CI：使用版本化/不可变 S3 key 以便重新部署先前构建。自动回滚 + 手册主要是 AWS 配置。',
    opsEn:['Enable CodeDeploy alarm/health-based auto-rollback (CloudWatch + minimum-healthy-hosts)','Pin container images by digest','Document & periodically test a manual rollback runbook'],
    opsZh:['启用 CodeDeploy 基于告警/健康的自动回滚（CloudWatch + 最小健康主机数）','按摘要锁定容器镜像','编写并定期演练手动回滚手册'] },
  'SEC-080': { d:[0.5,0.5], conf:'Med', g:'G18',
    en:'Code: configure Actuator + Micrometer to export metrics (Prometheus/CloudWatch registry). The alarms/SNS/SLOs are AWS + ops config.',
    zh:'代码：配置 Actuator + Micrometer 导出指标（Prometheus/CloudWatch registry）。告警/SNS/SLO 属 AWS + 运维配置。',
    opsEn:['Define CloudWatch alarms (process/5xx/latency/CPU/RDS) wired to SNS/PagerDuty','Re-enable AlarmConfiguration on the deployment group','Document SLO/SLA thresholds'],
    opsZh:['定义 CloudWatch 告警（进程/5xx/延迟/CPU/RDS）并接入 SNS/PagerDuty','在部署组重新启用 AlarmConfiguration','文档化 SLO/SLA 阈值'] },
  'SEC-081': { d:[0.25,0.5], conf:'High', g:'G17',
    en:'Code (script): make MonitorService.sh do a real readiness probe (curl the actuator health endpoint) with retry/backoff and fail on non-200; configure actuator readiness/liveness probe groups.',
    zh:'代码（脚本）：让 MonitorService.sh 执行带重试/退避的真实就绪探测（curl actuator health）并对非 200 失败；配置 actuator 就绪/存活探针分组。',
    opsEn:[], opsZh:[] },
  'SEC-083': { d:[0.25,0.25], conf:'High', g:'G17',
    en:'CI config: add waitForQualityGate(abortPipeline:true) after Sonar on release/PR builds (or correct CI_CD_DESIGN.md). Small; overlaps SEC-025.',
    zh:'CI 配置：在发布/PR 构建的 Sonar 后加 waitForQualityGate(abortPipeline:true)（或修正 CI_CD_DESIGN.md）。改动小；与 SEC-025 重叠。',
    opsEn:['Define the quality gate (fail on new Critical/High vulns) in SonarQube'],
    opsZh:['在 SonarQube 定义质量门禁（新增 Critical/High 漏洞即失败）'] },
  'SEC-085': { d:[1,2], conf:'Discuss', g:'G19',
    en:'Code (after process design): an authenticated export endpoint aggregating all PII for a subject (account, ticket PII, customer-contact PII, audit refs) to JSON, covering ticket contacts who are not users. Needs the DSAR intake/identity-verification workflow defined first.',
    zh:'代码（流程设计后）：一个经认证的导出端点，将某主体的全部 PII（账户、工单 PII、客户联系人 PII、审计引用）聚合为 JSON，并覆盖非用户的工单联系人。需先定义 DSAR 受理/身份核验流程。',
    opsEn:['Define the DSAR intake + identity-verification process (policy)'],
    opsZh:['定义 DSAR 受理 + 身份核验流程（策略）'] },
  'SEC-086': { d:[0.5,1], conf:'Med', g:'G19',
    en:'Code: make user deletion transactional — purge reset_password_token rows (deleteByUserId / ON DELETE CASCADE / orphanRemoval), pseudonymise audit/actor identity. Overlaps SEC-071/085.',
    zh:'代码：让用户删除事务化——清除 reset_password_token 行（deleteByUserId / ON DELETE CASCADE / orphanRemoval），对审计/actor 身份做假名化。与 SEC-071/085 重叠。',
    opsEn:[], opsZh:[] },
  'SEC-087': { d:[1,2], conf:'Discuss', g:'G19',
    en:'Code (front+back): show a privacy notice and capture consent at PII collection points (ticket submission, account provisioning), persist consent records (subject/purpose/notice-version/timestamp) in a new table, make exportable. Needs the lawful-basis/notice content decided first.',
    zh:'代码（前后端）：在 PII 采集点（工单提交、账户开通）展示隐私声明并捕获同意，将同意记录（主体/目的/声明版本/时间戳）持久化到新表并可导出。需先确定合法性基础/声明内容。',
    opsEn:['Decide lawful basis + draft privacy-notice content (legal)'],
    opsZh:['确定合法性基础 + 起草隐私声明内容（法务）'] },
  'SEC-088': { d:[1,2], conf:'Discuss', g:'G19',
    en:'Code (after policy): annotate confidential entities/columns (e.g. @Confidential), tag S3 objects, and drive log-masking from the classification. The org classification policy itself must exist first; rollout breadth is the variable.',
    zh:'代码（策略后）：标注机密实体/字段（如 @Confidential）、为 S3 对象打标签，并由分类驱动日志脱敏。需先有组织分类策略；推广覆盖面是变量。',
    opsEn:['Define the org data-classification policy (Public/Internal/Confidential/Restricted)'],
    opsZh:['制定组织数据分类策略（公开/内部/机密/受限）'] },
  'SEC-089': { d:[0.5,1], conf:'Med', g:'G19',
    en:'Code: a scheduled purge that hard-deletes/anonymizes soft-deleted customer (IE-instance) data + dependents after the retention window, cascading to S3; record destruction in the audit log. Overlaps SEC-075/027.',
    zh:'代码：一个定时清理作业，在留存期后对软删除的客户（IE 实例）数据及依赖做硬删除/匿名化并级联到 S3；在审计日志记录销毁。与 SEC-075/027 重叠。',
    opsEn:['Agree the retention schedule (policy)'],
    opsZh:['确定留存计划（策略）'] },
  'SEC-090': { d:[0.5,1], conf:'Med', g:'G19',
    en:'Code: wire the destruction workflow — call ShareFile deleteItem + S3 deleteObject for ticket attachments on resolve/retention; remove or integrate the dead deleteItem path; audit destructions.',
    zh:'代码：打通销毁流程——在解决/到期时对工单附件调用 ShareFile deleteItem 与 S3 deleteObject；移除或整合失效的 deleteItem 路径；审计销毁。',
    opsEn:['Configure S3 lifecycle expiration + object-lock/versioning on the confidential bucket'],
    opsZh:['为机密桶配置 S3 生命周期过期 + 对象锁/版本控制'] },
  'SEC-067': { d:[0.5,1], conf:'Med', g:'G14',
    en:'Code: audit every user/role/permission CRUD with actor/target/before-after, ideally by activating the dormant @Auditable aspect. Shares the audit mechanism with SEC-028.',
    zh:'代码：审计所有用户/角色/权限 CRUD 的操作者/目标/前后值，最好启用沉睡的 @Auditable 切面。与 SEC-028 共用审计机制。',
    opsEn:['Route records to the immutable audit destination (SEC-029)'],
    opsZh:['将记录路由到不可变审计目的地（SEC-029）'] },
  'SEC-082': { d:[0.25,0.25], conf:'High', g:'G18',
    en:'Config: add restart:unless-stopped to the three services in compose and a HEALTHCHECK to each Dockerfile. Trivial.',
    zh:'配置：在 compose 为三个服务加 restart:unless-stopped，并在每个 Dockerfile 加 HEALTHCHECK。改动极小。',
    opsEn:['Optionally run >=2 replicas behind a load balancer (infra)'],
    opsZh:['可选：在负载均衡后运行 ≥2 副本（基础设施）'] },
  'SEC-084': { d:[0.25,0.25], conf:'High', g:'G17',
    en:'CI config: remove **/resources/** from sonar.exclusions, set sonar.sources, enable secret/security-hotspot rules, run on release/PR. Config-file edit; overlaps SEC-025/083.',
    zh:'CI 配置：从 sonar.exclusions 移除 **/resources/**，设置 sonar.sources，启用密钥/安全热点规则并在发布/PR 运行。配置文件改动；与 SEC-025/083 重叠。',
    opsEn:[], opsZh:[] },
  'SEC-065': { d:[0.25,0.5], conf:'Med', g:'G20',
    en:'Code: remove the unwired stubbed license-key auth path (provider + filter) if unused, or implement real validation mirroring LicenseValidator.validate before wiring it; add a rejection test. Decision + small implementation.',
    zh:'代码：若未使用则移除未接线的桩式 license-key 认证路径（provider + filter），或在接线前实现仿照 LicenseValidator.validate 的真实校验；并加拒绝测试。决策 + 小幅实现。',
    opsEn:[], opsZh:[] },
};

module.exports = { GROUPS, CONF, EST };
